source 'https://rubygems.org'
ruby '2.0.0'

#gem "passenger", ">= 5.0.25", require: "phusion_passenger/rack_handler"
gem 'sinatra', '1.4.6', :require => 'sinatra/base'
gem 'unicorn', '4.6.3'
gem 'erubis'
gem 'builder'
gem 'i18n', '~> 0.6.9'
gem 'activesupport', '~> 4.1.1'
gem 'nokogiri', '1.6.0'
gem 'nestful', '1.0.2'
gem 'bcrypt-ruby', '3.1.1'
gem 'rack-ssl', '1.3.3'
gem 'omniauth-twitter', '1.0.0'
gem 'omniauth-github', '1.1.1'
gem 'rake', '10.1.0'
gem 'rdiscount', '2.1.6'
gem 'mail'
gem 'twitter'
gem 'closure-compiler', '1.1.10'
gem 'yui-compressor', '0.11.0'
gem 'dedent', '0.0.2'
gem 'dalli', '2.6.4'
gem 'memcachier'
gem 'sanitize', '2.0.6'
gem 'redis', '3.0.4'
gem 'gibbon', :git => 'https://github.com/amro/gibbon.git'
gem 'dotenv', '0.9.0'
gem 'addressable'

group :development do
  gem 'thin'
end

# DB
gem 'sequel', '4.0.0'
gem 'sinatra-sequel'
gem 'sequel_postgresql_triggers', '1.0.3'
gem 'pg', '0.16.0'

# Assets
gem 'sprockets', '2.9.3'
gem 'sprockets-commonjs', '0.0.6'
gem 'uglifier', '2.1.2'
gem 'coffee-script', '2.2.0'
gem 'coffee-script-source', '1.6.3'
gem 'stylus', '0.7.2'
gem 'stylus-source', '0.31.0'
gem 'eco'
gem 'json', '~> 1.7.7'
gem 'cft-source', '>= 0.0.6'
